"use client";

import { DatabaseZap, Loader2, Play, WandSparkles } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { QueryExecutionResponse, executeSql, generateSql } from "@/lib/api";

export default function QueryPage() {
  const [question, setQuestion] = useState("Show revenue by customer segment for the last 90 days.");
  const [sql, setSql] = useState("select segment, revenue from revenue_by_segment");
  const [result, setResult] = useState<QueryExecutionResponse | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isExecuting, setIsExecuting] = useState(false);

  const token = useMemo(() => {
    if (typeof window === "undefined") {
      return "";
    }

    return window.localStorage.getItem("analytics_access_token") ?? "";
  }, []);

  async function handleGenerate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setIsGenerating(true);
    setMessage(null);

    try {
      const generated = await generateSql(token, question);
      setSql(generated.sql);
      setMessage(`Generated by ${generated.provider} with ${generated.confidence} confidence.`);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "SQL generation failed");
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleExecute() {
    setIsExecuting(true);
    setMessage(null);

    try {
      setResult(await executeSql(token, sql, 100));
    } catch (error) {
      setResult(null);
      setMessage(error instanceof Error ? error.message : "Query execution failed");
    } finally {
      setIsExecuting(false);
    }
  }

  return (
    <main className="min-h-screen bg-background">
      <header className="border-b bg-white px-5 py-4">
        <div className="mx-auto flex max-w-7xl items-center justify-between gap-4">
          <div>
            <h1 className="text-xl font-semibold">Natural language query</h1>
            <p className="text-sm text-muted-foreground">
              Generate SQL contracts and execute read-only analytics queries.
            </p>
          </div>
          <Badge variant="secondary">Read-only SQL</Badge>
        </div>
      </header>

      <section className="mx-auto grid max-w-7xl gap-5 p-5 xl:grid-cols-[460px_1fr]">
        <div className="grid gap-5">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <WandSparkles className="h-4 w-4 text-primary" aria-hidden="true" />
                Ask a question
              </CardTitle>
              <CardDescription>AI SQL generation is disabled until a provider is configured.</CardDescription>
            </CardHeader>
            <CardContent>
              <form className="space-y-4" onSubmit={handleGenerate}>
                <div className="space-y-2">
                  <Label htmlFor="question">Question</Label>
                  <Textarea
                    id="question"
                    value={question}
                    onChange={(event) => setQuestion(event.target.value)}
                  />
                </div>
                <Button className="w-full gap-2" disabled={isGenerating || !token} type="submit">
                  {isGenerating ? (
                    <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                  ) : (
                    <WandSparkles className="h-4 w-4" aria-hidden="true" />
                  )}
                  Generate SQL
                </Button>
              </form>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <DatabaseZap className="h-4 w-4 text-primary" aria-hidden="true" />
                SQL editor
              </CardTitle>
              <CardDescription>Only one PostgreSQL SELECT statement is accepted.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <Textarea
                className="min-h-40 font-mono"
                value={sql}
                onChange={(event) => setSql(event.target.value)}
              />
              <Button className="w-full gap-2" disabled={isExecuting || !token} onClick={handleExecute}>
                {isExecuting ? (
                  <Loader2 className="h-4 w-4 animate-spin" aria-hidden="true" />
                ) : (
                  <Play className="h-4 w-4" aria-hidden="true" />
                )}
                Execute query
              </Button>
              {!token ? (
                <p className="text-sm text-muted-foreground">Sign in before running workspace queries.</p>
              ) : null}
              {message ? <p className="text-sm font-medium text-muted-foreground">{message}</p> : null}
            </CardContent>
          </Card>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Results</CardTitle>
            <CardDescription>
              {result ? `${result.row_count} rows returned` : "Run a query to populate results."}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {result && result.rows.length > 0 ? (
              <div className="overflow-auto rounded-md border">
                <table className="w-full min-w-[640px] border-collapse text-sm">
                  <thead className="bg-muted">
                    <tr>
                      {result.columns.map((column) => (
                        <th key={column} className="border-b px-3 py-2 text-left font-semibold">
                          {column}
                        </th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {result.rows.map((row, rowIndex) => (
                      <tr key={rowIndex} className="border-b last:border-b-0">
                        {result.columns.map((column) => (
                          <td key={column} className="px-3 py-2 text-muted-foreground">
                            {String(row[column] ?? "")}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="grid min-h-96 place-items-center rounded-md border bg-muted/30 text-sm text-muted-foreground">
                No results yet
              </div>
            )}
          </CardContent>
        </Card>
      </section>
    </main>
  );
}

